// <auto-generated />
namespace Tip4Trip_aka.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userOfHouse2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userOfHouse2));
        
        string IMigrationMetadata.Id
        {
            get { return "201905030128440_userOfHouse2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
