// <auto-generated />
namespace Tip4Trip_aka.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _11052019_01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_11052019_01));
        
        string IMigrationMetadata.Id
        {
            get { return "201905121355084_11052019_01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
